### ISSUE TITLE
Organization: clone in travis.yml VS submodule

### ISSUE THREAD

**Issue by michaelhsmart** [wavelab/ros_docker_ci#10]
There are currently two candidate ways we can design the usage of this repo.

**Submodule**
This is the current default.

Pros:
- Transparency: I would argue that the submoduling is more transparent because the link to this repo is encoded through a submodule which is directly visible as a dependency.
- Similarity for local builds: If the CI aspects are submoduled within the repo it is easier to test them out on your local machine. For example with the submodule approach, I just have to set the environment variables as would be done in `.travis.yml` and then I can directly work with the docker container and call the CI scripts directly on my local machine. Otherwise we have to add the git clone as a step whenever someone wants to replicate the travis-CI build to debug the docker CI build locally.

Cons:
- Submoduling: There a few general pains with submoduling repos that are perfectly legitimate. That said, we don't plan on this repo being updated very frequently (if ever) after it is initially rolled out.

**Git Clone**

Pros:
- Cleanliness: We avoid tangling in submodules and keep the user repo in a cleaner state relative to CI. The only place we need to add in CI materials is then in `.travis.yml`.

Cons:
- CI/Local divergence: Recreating the CI build in a local build will require the extra git clone steps. Not too significant but worth considering.

**Comment by icolwell** [comment]
Great points. For something as complex as this docker build system, trying things out/debugging locally is a huge pro. Probably best to leave as a submodule. The clone strategy is nice, but probably best to leave for simpler things.

**Comment by michaelhsmart** [comment]
Decision: We'll keep it as a submodule.
