### ISSUE TITLE
ROS_DISTRO variable issue

### ISSUE THREAD

**Issue by yuzhangbit** [wavelab/ros_docker_ci#14]
According to the [example](https://github.com/wavelab/ros_docker_ci_demo), the script is responsible for identifying the OS version and exporting the `ROS_DISTRO`.  And the user's OS won't export `ROS_DISTRO` itself anyway.  So the docker `ENV ROS_DISTRO` is not needed.

A suspicious script running order issue is observed [here]( https://github.com/wavelab/ros_docker_ci_demo/blob/master/scripts/run-ci-tests.bash#L6)

The `source /opt/ros/${ROS_DISTRO}/setup.bash` need run after `source $SCRIPT_DIR/identify_environment.bash`, or the build will fail if the users don't source the ros setup themselves.  

I guess the example doesn't fail because of `ENV ROS_DISTRO` in the docker.

**Comment by michaelhsmart** [comment]
That's a bug. The demo script order needs to be flipped.

I'll make an issue for it on that repo.

**Comment by michaelhsmart** [comment]
This actually hints at a different issue as well. The docker ENV's should match whatever we typically expect to have on an appropriately configured clean VM and have our scripts be sensitive to making sure the rest is covered.

Created #15 .

**Comment by michaelhsmart** [comment]
Demo issue has been fixed:
https://github.com/wavelab/ros_docker_ci_demo/commit/262daf25050aaad30fc1a998264a8d384cc5f707
